trainer:
  name: SupervisedTrainer
  args:
device:
  name: get_device
  args:
    default: cuda
model:
  name: mobilevit_xs
criterion:
  name: ClassificationCELoss

optimizer:
  name: Adam
  args:
    lr: 0.0001
    
metric:
  - name: ClassificationAccuracy
    args:
scheduler:
  name: StepLR
  args:
    step_size: 3
    gamma: 0.2
    last_epoch: -1

data: # instruction here
  splits:
    train: 0.6
    val: 0.4
  dataset:
    train:
      name: CATEMOTIONDATASET
      args:
        root_dir: "/mnt/ai_data/DanhAI/cat_emotion_classification"
        annotation_file: "train_annotation.csv"
    val:
      name: CATEMOTIONDATASET
      args:
        root_dir: "/mnt/ai_data/DanhAI/cat_emotion_classification"
        annotation_file: "valid_annotation.csv"

  loader:
    train:
      name: DataLoader
      args:
        batch_size: 32
        shuffle: True
        drop_last: True
    val:
      name: DataLoader
      args:
        batch_size: 8
        shuffle: False
        drop_last: False