learner:
  name: SupervisedTrainer
  args:
device:
  name: get_device
  args:
    default: cuda
model:
  name: mobilevit_xxs
criterion:
  name: Huberwithstat

optimizer:
  name: Adam
  args:
    lr: 0.0001
    
metric:
  - name: Accuracy
    args:
scheduler:
  name: StepLR
  args:
    step_size: 3
    gamma: 0.2
    last_epoch: -1

data: # instruction here
  splits:
    train: 0.6
    val: 0.4
  dataset:
    train:
      name: DATASET
      args:
        root_dir: "/mnt/ai_data/DanhAI/Face_project/datasets/AFAD-Full"
        annotation_file: "train.csv"
    val:
      name: AFADDataset
      args:
        root_dir: "/mnt/ai_data/DanhAI/Face_project/datasets/AFAD-Full"
        annotation_file: "val.csv"

  loader:
    train:
      name: DataLoader
      args:
        batch_size: 2
        shuffle: True
        drop_last: True
    val:
      name: DataLoader
      args:
        batch_size: 2
        shuffle: False
        drop_last: False