train:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          height: 256
          width: 256
      - name: AlbNormalize
        args:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
      - name: AlbToTensorV2
      

val:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          height: 256
          width: 256
      - name: AlbNormalize
        args:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
      - name: AlbToTensorV2
      